name: Debug Knative logs

on:
  workflow_dispatch:
    inputs:
      gsutil:
        description: 'gsutil command'
        required: true

jobs:

  analyze:
    runs-on: ubuntu-latest
    env:
      SACURA_LOG_PATH: "./sacura/sacura/sacura-vcnvm-sacura.log"
      COMPONENTS_PATHS: "./knative-eventing/kafka-broker-dispatcher,./knative-eventing/kafka-broker-receiver"
      OUT_PATH: "./out.json"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install gsutil
        run: |
          set -e
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get -y install apt-transport-https ca-certificates gnupg
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get -y update && sudo apt-get -y install google-cloud-sdk


      - name: Download artifacts
        run: |
          set -e

          ${{ github.event.inputs.gsutil }}

          ls -lR

      - name: Download artifacts
        run: go run cmd/sacura/sacura_logs.go

      - uses: actions/upload-artifact@v2
        name: Upload Output
        with:
          path: ${{ env.OUT_PATH }}